version: '3'
services:

  front-end:
    build:
      context: ./../front-end
      dockerfile: ./../front-end/Dockerfile
    ports:
      - "80:80"

  api-gateway:
    build: 
      context: ./../api-gateway
      dockerfile: ./../api-gateway/Dockerfile
    ports:
      - "5000:5000"
      
  movie-service:
    build: 
      context: ./../movie-service
      dockerfile: ./../movie-service/Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=db-movie:3306
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=movie
      - DB_DRIVER=mysql

  auth-service:
    build: 
      context: ./../auth-service
      dockerfile: ./../auth-service/Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=db-user:3307
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=user
      - DB_DRIVER=mysql
      - JWT_SECRET=${JWT_SECRET}
      
  db-movie:
    image: mysql
    container_name: db-movie
    volumes:
      - "./scripts/schema-movie.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: movie
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - '3306:3306'

  db-user:
    image: mysql
    container_name: db-user
    volumes:
      - "./scripts/schema-user.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: user
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'

  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
